### ISSUE TITLE
Changelog for Self hosting

### ISSUE THREAD

**Issue by rperryng** [kamilkisiela/graphql-hive#1135]
Hello!

I was wondering if there is any intention of publishing a changelog related to hive's docker images for self-hosting, mainly around breaking changes.

I understand that rapid development is still underway and that some versioning system is intended for the published docker images in the future - but perhaps in the meantime there are a few things that could be already be automated such as when new required secrets are introduced? (i would be happy to contribute with some direction :) )

---

Additionally, can I ask what the `CDN_AUTH_PRIVATE_KEY` in the `server` package is for?  We are not using a CDN for our hosted configuration so is it still necessary to generate/include a value for this (it is currently marked as required)?  It also seems all the AWS related secrets are specific to the CDN package, so should all the AWS-related env vars really  be marked as required?

**Comment by rperryng** [comment]
Just to add, i simply threw in some dummy credentials for the AWS access-related env secrets and it seems the app works perfectly fine - perhaps these aren't truly required?

**Comment by n1ru4l** [comment]
@rperryng Regarding the `CDN_AUTH_PRIVATE_KEY`, this is a secret that will be used for generating the "legacy" CDN access keys.
We actually removed this part on yesterday (27.01), the environment variable is some leftover code that will be removed by https://github.com/kamilkisiela/graphql-hive/pull/1165. Sorry for the inconvenience!

For the self-hosted version, there is a local "CDN" that is exposed on the `server` container under the `/artifacts route. It exposes the same functionality as the cloud CDN - however, without the high availability part. 😇

There are no AWS-related environment variables, only S3-related environment variables. S3-compatible storage is a crucial part of the Hive stack and might be used by more parts of Hive in the future, thus just setting them to "noop" values is not recommended. Right now it is used for both storing target artifacts and cdn access tokens.

____

Properly handling versioning, upgrade guides, etc. is one of the challenges we still need to solve very soon in order to make upgrading for self-hosters as smooth as possible.

**Comment by rperryng** [comment]
Thank you for the clarification :)
