### ISSUE TITLE
could we add other native plugins to hive custom build “Apollo Router” binary?

### ISSUE THREAD

**Issue by sianwunlai-houzz** [kamilkisiela/graphql-hive#2547]
Hi team, we have our own plugins, is it possible to utilize them by your custom build binary/docker image??? as I know if need to include custom plugins [we must build a custom apollo router binary](https://www.apollographql.com/docs/router/customizations/custom-binary)?

**Comment by kamilkisiela** [comment]
If you want to use a rust-written plugin with Apollo Router, you need to build it from source code.
Many of our users do it this way, I would say most of them, because of the need for custom plugins.

To build it from source with GraphQL Hive you can follow the instructions [here](https://the-guild.dev/graphql/hive/docs/integrations/apollo-router) (see "Custom" tab).

**Comment by sianwunlai-houzz** [comment]
thanks, I didn't notice the `Custom` tab 🙇
