### ISSUE TITLE
Update axios to `1.6.0` as its vulnerable currently

### ISSUE THREAD

**Issue by TomPeas** [kamilkisiela/graphql-hive#3232]
### Discussed in https://github.com/kamilkisiela/graphql-hive/discussions/3229

<div type='discussions-op-text'>

<sup>Originally posted by **TomPeas** October 31, 2023</sup>
The version of axios used by `@graphql-hive/client` is vulnerable: https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459</div>

**Comment by dotansimha** [comment]
Thanks, @TomPeas for reporting it. 
Since we are using `^1.2` at the moment, you can update the nested dependency by reinstalling the Hive package, or, use your package manager to update the nested dependency. You are getting an older version because of the lock file you have in your project. 

<img width="650" alt="image" src="https://github.com/kamilkisiela/graphql-hive/assets/3680083/28b6b8b0-df7a-491a-b49e-771d2489413c">

But, to allow easier upgrade flow, and to be more explicit, I've created this PR to update the range of `axios`: https://github.com/kamilkisiela/graphql-hive/pull/3237

We will merge and release this when CI clears.

**Comment by dotansimha** [comment]
Fixed and released in `@graphql-hive/client@0.25.0`.
