### ISSUE TITLE
Support Okta

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#468]

**Comment by n1ru4l** [comment]
Okta offers multiple solutions.

## Single Sign On (SSO) via OAuth 2.0 Open ID Connect (OCID)

Like Google and GitHub login. This is easily implemented as a custom SuperTokens provider.

Learn more:
- https://www.youtube.com/watch?v=996OiexHze0
- https://developer.okta.com/docs/concepts/oauth-openid/
- https://en.wikipedia.org/wiki/OpenID

## Single Sign On (SSO) via Security Assertion Markup Language (SAML 2.0)

Kind of like OCID but uses XML lol.
Requires extra steps (services) for integrating SAML into SuperTokens.

Learn more:
- https://developer.okta.com/docs/concepts/saml/
- https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language
- https://supertokens.com/docs/thirdpartyemailpassword/common-customizations/saml/saml-login

## System for Cross-domain Identity Management (SCIM)

A protocol for provisioning/syncing user accounts and permissions from Okta to Hive.
In order to use this we need to build an API and also use SAML SSO as Okta does not support SCIM via OCID

Learn more:
- https://developer.okta.com/docs/concepts/scim/
- https://en.wikipedia.org/wiki/System_for_Cross-domain_Identity_Management

**Comment by n1ru4l** [comment]
In order to allow multiple Okta organizations to sign into Hive using the same Hive Okta Integration ([multi-tenancy](https://developer.okta.com/docs/guides/oin-oidc-multi-tenancy/main/)) we need to put our integration onto the [Okta Integration Network (OIN)](https://developer.okta.com/docs/guides/okta-integration-network/).

This first requires building a successful Okta integration and then kicking off the [OIN publish process](https://developer.okta.com/docs/guides/submit-app/openidconnect/main/).

**Comment by n1ru4l** [comment]
I created https://github.com/kamilkisiela/graphql-hive/pull/510 for adding OCID SSO

**Comment by kamilkisiela** [comment]
#524

**Comment by n1ru4l** [comment]
This is now implemented https://www.the-guild.dev/blog/announcing-free-single-sign-on-for-graphql-hive
