### ISSUE TITLE
hive dev - option to exclude unspecified subgraphs

### ISSUE THREAD

**Issue by kamilkisiela** [kamilkisiela/graphql-hive#5113]
Currently, `hive dev` includes schemas from all subgraphs in the supergraph, even when not specified in the CLI.
We need to implement a flag/option, allowing users to use only the provided subgraphs in the supergraph generation process.

**Comment by klippx** [comment]
With rover we were able to "omit" certain graphs from the superschema or even contributing to `supergraph.graphql`, if they were not part of the config. Rover takes a `supergraph.yaml` config file, which contains the list of graphs that should be composed. Let's say `a-dgs`, `b-dgs`, and `c-dgs`, along with the path to their schema and the URL to they should route to. As an example, if we do not add `d-dgs` and `e-dgs` to this configuration file, then in the end whatever is in those two subgraphs do not make it to the `supergraph.graphql`.

When using the Hive CLI, the equivalent would be to do: 

```
hive dev \
  --prune \
  --service a-dgs --url http://localhost:3006 \
  --service b-dgs --url http://localhost:3007 \
  --service c-dgs --url http://localhost:3008
```

In other words, we only supply those subgraphs we are concerned* about.

*) The use case could be "wip" subgraphs or a feature to disable subgraphs for any other reason (only active in development, and only for those teams that actively enable it to work on it, etc).

The big difference though is that the `supergraph.graphql` that this Hive CLI command produces will still contain the schema from `d-dgs` and `e-dgs`, even though I did not provide those arguments. The result is that queries from `d-dgs` and `e-dgs` are exposed that cannot be routed, since the arguments did not provide the appropriate routing URLs. It will not error or fail at this step, but instead it will use the docker/kubernetes networking alias instead (which is irrellevant how it found, but perhaps Hive CLI grabbed it by introspecting Hive CDN):

```
HTTP fetch failed from 'd-dgs': HTTP fetch failed from 'd-dgs': error trying to connect: dns error: no record found for Query { name: Name(\"d-dgs.\"), query_type: AAAA, query_class: IN }
in supergraph.graphql
D_DGS @join__graph(name: "d-dgs", url: "http://d-dgs/") 
```

Since this behaviour is just different between `rover` and `hive` perhaps we need to add a new cmd line flag such as `--prune` that opts in to a more `rover`-esque behaviour:
```
hive dev \
  --prune \
  --service a-dgs --url http://localhost:3006 \
  --service b-dgs --url http://localhost:3007 \
  --service c-dgs --url http://localhost:3008
```

The `--prune` flag would change the behaviour in such a way that composition would drop the schemas from any subgraph that was not explicitly provided (similar to `supergraph.yaml`) and try to compose only the remaining (provided) schemas. Thus, omitted schemas would not contribute to federation and any root queries from omitted subgraphs would not be available in `supergraph.graphql`, any unreferenced types would be omitted, etc.
