### ISSUE TITLE
graphiql should be full page in lab 

### ISSUE THREAD

**Issue by saihaj** [kamilkisiela/graphql-hive#77]
![image](https://user-images.githubusercontent.com/44710980/170138719-cf1aefcf-a5c7-45e7-9288-3a087bd57d13.png)

**Comment by dotansimha** [comment]
Also, @B2o5T, I think we had a `Connect` button here in the older design? that shows a modal with the instructions for using the Hive schema with other tools. I think we can drop the old Lab-specific token and setup we have, and just point the users to use the CDN schema instead? (we can reuse the same modal and instructions from the `Schema` page, just point to a different CDN link (should be `/introspection` or `/sdl` instead of the default root CDN endpoint)
